name: DevHub CI (Dockerized)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t devhub-api .

      - name: Run container and test
        run: |
          docker run --rm \
            -e DJANGO_SETTINGS_MODULE=devhub_api.settings \
            -e DEBUG=True \
            devhub-api \
            sh -c "pytest -v"
